#!/usr/bin/env python3
"""Create the 4 security issues in the Superset fork.

Usage:
    python scripts/create_issues.py

Requires: GITHUB_TOKEN env var with repo scope
Optional: SUPERSET_REPO env var (default: bsunders/superset)
"""

import json
import os
import sys
import urllib.request
import urllib.error

REPO = os.environ.get("SUPERSET_REPO", "bsunders/superset")
TOKEN = os.environ.get("GITHUB_TOKEN", "")
API = "https://api.github.com"

if not TOKEN:
    print("ERROR: GITHUB_TOKEN env var is required")
    print("Run: set GITHUB_TOKEN=ghp_your_token_here  (Windows)")
    print(" or: export GITHUB_TOKEN=ghp_your_token_here  (Mac/Linux)")
    sys.exit(1)

HEADERS = {
    "Authorization": f"token {TOKEN}",
    "Accept": "application/vnd.github.v3+json",
    "Content-Type": "application/json",
}

ISSUES = [
    {
        "title": "[HIGH] CVE-2026-27205: Upgrade flask from 2.3.3 to 3.1.3",
        "labels": ["devin-remediate"],
        "body": """## Security Vulnerability: CVE-2026-27205

**Package:** `flask` (current: `2.3.3`)
**Severity:** HIGH
**Ecosystem:** python
**Fix version:** `3.1.3`

### Description
Flask 2.3.3 has a known vulnerability (CVE-2026-27205). The fix is available in version 3.1.3.

### Remediation Instructions
Upgrade `flask` from `2.3.3` to `3.1.3` in the project dependencies. The version pin is in `requirements/base.in` and compiled to `requirements/base.txt`. Update the pin and recompile. Check for any breaking API changes between Flask 2.x and 3.x. Run the test suite to verify nothing is broken.

### Acceptance Criteria
- [ ] Vulnerability CVE-2026-27205 is no longer reported by pip-audit
- [ ] All existing tests pass
- [ ] PR links back to this issue

---
*Auto-generated by Security Remediation Pipeline*""",
    },
    {
        "title": "[HIGH] PYSEC-2026-113: Upgrade pyarrow from 20.0.0 to 23.0.1",
        "labels": ["devin-remediate"],
        "body": """## Security Vulnerability: PYSEC-2026-113

**Package:** `pyarrow` (current: `20.0.0`)
**Severity:** HIGH
**Ecosystem:** python
**Fix version:** `23.0.1`

### Description
PyArrow 20.0.0 has a known vulnerability (PYSEC-2026-113). The fix is available in version 23.0.1.

### Remediation Instructions
Upgrade `pyarrow` from `20.0.0` to `23.0.1` in the project dependencies. The version constraint is in `pyproject.toml` and/or `requirements/base.in`. Update the constraint and recompile requirements. PyArrow major version changes can include breaking API changes - verify all code that imports pyarrow still works.

### Acceptance Criteria
- [ ] Vulnerability PYSEC-2026-113 is no longer reported by pip-audit
- [ ] All existing tests pass
- [ ] PR links back to this issue

---
*Auto-generated by Security Remediation Pipeline*""",
    },
    {
        "title": "[HIGH] CVE-2026-44405: Investigate paramiko 3.5.1 vulnerability",
        "labels": ["devin-remediate"],
        "body": """## Security Vulnerability: CVE-2026-44405

**Package:** `paramiko` (current: `3.5.1`)
**Severity:** HIGH
**Ecosystem:** python
**Fix version:** No fix available yet

### Description
Paramiko 3.5.1 has a known vulnerability (CVE-2026-44405). No fix version is currently available.

### Remediation Instructions
Investigate whether paramiko can be upgraded to a newer version that addresses CVE-2026-44405. Check the paramiko changelog and security advisories. If no fix is available, document the risk and check if the vulnerable code path is exercised in Superset's usage of paramiko (used for SSH tunneling in database connections). If possible, pin to a safe version or add a code-level mitigation.

### Acceptance Criteria
- [ ] Investigation documented in PR description
- [ ] If fix available: vulnerability no longer reported
- [ ] If no fix: risk assessment documented, mitigation applied if possible
- [ ] PR links back to this issue

---
*Auto-generated by Security Remediation Pipeline*""",
    },
    {
        "title": "[CRITICAL] GHSA-55h3-fm53-wq99: Remove malware package eslint-plugin-i18n-strings",
        "labels": ["devin-remediate"],
        "body": """## Security Vulnerability: GHSA-55h3-fm53-wq99

**Package:** `eslint-plugin-i18n-strings` (npm)
**Severity:** CRITICAL
**Ecosystem:** npm
**Fix version:** No safe version exists - package contains malware

### Description
The npm package `eslint-plugin-i18n-strings` has been flagged as containing malware (GHSA-55h3-fm53-wq99). This package must be removed from the project entirely.

### Remediation Instructions
1. Remove `eslint-plugin-i18n-strings` from `superset-frontend/package.json` (or wherever it is referenced)
2. Remove any ESLint configuration that references this plugin
3. If custom lint rules from this plugin are in use, migrate them to a safe alternative or implement them as local ESLint rules
4. Run `npm install` to update the lockfile
5. Run the linting and test suites to verify nothing is broken

### Acceptance Criteria
- [ ] Package `eslint-plugin-i18n-strings` completely removed from dependencies and lockfile
- [ ] ESLint configuration updated to remove references to this plugin
- [ ] Linting still passes (with any rule migrations needed)
- [ ] All existing tests pass
- [ ] PR links back to this issue

---
*Auto-generated by Security Remediation Pipeline*""",
    },
]


def api_request(method, url, data=None):
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=HEADERS, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        err_body = e.read().decode() if e.fp else ""
        print(f"  ERROR {e.code}: {err_body[:200]}")
        return None


def main():
    # Ensure label exists
    print("Ensuring 'devin-remediate' label exists...")
    api_request("POST", f"{API}/repos/{REPO}/labels", {
        "name": "devin-remediate",
        "color": "d73a4a",
        "description": "Automated remediation by Devin",
    })

    print()
    print("=== Creating issues ===")

    for i, issue in enumerate(ISSUES, 1):
        short = issue["title"].split(":")[0]
        print(f"{i}/4: {short}...")
        result = api_request("POST", f"{API}/repos/{REPO}/issues", issue)
        if result:
            print(f"  Created issue #{result['number']}: {result['html_url']}")
        else:
            print(f"  Failed to create issue: {issue['title'][:60]}")

    print()
    print("=== All 4 issues created ===")
    print()
    print("Next step - trigger Devin sessions:")
    print("  curl -X POST http://localhost:8000/api/trigger-all")
    print()
    print("Make sure Docker is running first:")
    print("  docker-compose up --build")


if __name__ == "__main__":
    main()
