@echo off
REM Create the 4 security issues in the Superset fork.
REM Usage: scripts\create-issues.bat
REM
REM Requires: GITHUB_TOKEN env var with repo scope
REM Tip: run "set GITHUB_TOKEN=ghp_..." or load from .env first

setlocal enabledelayedexpansion

if "%SUPERSET_REPO%"=="" set "SUPERSET_REPO=bsunders/superset"
set "API=https://api.github.com"

if "%GITHUB_TOKEN%"=="" (
    echo ERROR: GITHUB_TOKEN env var is required
    echo Run: set GITHUB_TOKEN=ghp_your_token_here
    exit /b 1
)

set "AUTH=Authorization: token %GITHUB_TOKEN%"
set "ACCEPT=Accept: application/vnd.github.v3+json"

echo Ensuring 'devin-remediate' label exists...
curl -s -X POST -H "%AUTH%" -H "%ACCEPT%" "%API%/repos/%SUPERSET_REPO%/labels" -d "{\"name\":\"devin-remediate\",\"color\":\"d73a4a\",\"description\":\"Automated remediation by Devin\"}" >nul 2>&1

echo.
echo === Creating issues ===

echo 1/4: Flask CVE-2026-27205
curl -s -X POST -H "%AUTH%" -H "%ACCEPT%" "%API%/repos/%SUPERSET_REPO%/issues" -d "{\"title\":\"[HIGH] CVE-2026-27205: Upgrade flask from 2.3.3 to 3.1.3\",\"labels\":[\"devin-remediate\"],\"body\":\"## Security Vulnerability: CVE-2026-27205\\n\\n**Package:** `flask` (current: `2.3.3`)\\n**Severity:** HIGH\\n**Ecosystem:** python\\n**Fix version:** `3.1.3`\\n\\n### Description\\nFlask 2.3.3 has a known vulnerability (CVE-2026-27205). The fix is available in version 3.1.3.\\n\\n### Remediation Instructions\\nUpgrade `flask` from `2.3.3` to `3.1.3` in the project dependencies. The version pin is in `requirements/base.in` and compiled to `requirements/base.txt`. Update the pin and recompile. Check for any breaking API changes between Flask 2.x and 3.x. Run the test suite to verify nothing is broken.\\n\\n### Acceptance Criteria\\n- [ ] Vulnerability CVE-2026-27205 is no longer reported by pip-audit\\n- [ ] All existing tests pass\\n- [ ] PR links back to this issue\\n\\n---\\n*Auto-generated by Security Remediation Pipeline*\"}" | python -c "import json,sys;d=json.load(sys.stdin);print(f'  Created issue #{d.get(\"number\",\"ERROR\")}: {d.get(\"html_url\",\"ERROR\")}')"

echo 2/4: PyArrow PYSEC-2026-113
curl -s -X POST -H "%AUTH%" -H "%ACCEPT%" "%API%/repos/%SUPERSET_REPO%/issues" -d "{\"title\":\"[HIGH] PYSEC-2026-113: Upgrade pyarrow from 20.0.0 to 23.0.1\",\"labels\":[\"devin-remediate\"],\"body\":\"## Security Vulnerability: PYSEC-2026-113\\n\\n**Package:** `pyarrow` (current: `20.0.0`)\\n**Severity:** HIGH\\n**Ecosystem:** python\\n**Fix version:** `23.0.1`\\n\\n### Description\\nPyArrow 20.0.0 has a known vulnerability (PYSEC-2026-113). The fix is available in version 23.0.1.\\n\\n### Remediation Instructions\\nUpgrade `pyarrow` from `20.0.0` to `23.0.1` in the project dependencies. The version constraint is in `pyproject.toml` and/or `requirements/base.in`. Update the constraint and recompile requirements. PyArrow major version changes can include breaking API changes - verify all code that imports pyarrow still works.\\n\\n### Acceptance Criteria\\n- [ ] Vulnerability PYSEC-2026-113 is no longer reported by pip-audit\\n- [ ] All existing tests pass\\n- [ ] PR links back to this issue\\n\\n---\\n*Auto-generated by Security Remediation Pipeline*\"}" | python -c "import json,sys;d=json.load(sys.stdin);print(f'  Created issue #{d.get(\"number\",\"ERROR\")}: {d.get(\"html_url\",\"ERROR\")}')"

echo 3/4: Paramiko CVE-2026-44405
curl -s -X POST -H "%AUTH%" -H "%ACCEPT%" "%API%/repos/%SUPERSET_REPO%/issues" -d "{\"title\":\"[HIGH] CVE-2026-44405: Investigate paramiko 3.5.1 vulnerability\",\"labels\":[\"devin-remediate\"],\"body\":\"## Security Vulnerability: CVE-2026-44405\\n\\n**Package:** `paramiko` (current: `3.5.1`)\\n**Severity:** HIGH\\n**Ecosystem:** python\\n**Fix version:** No fix available yet\\n\\n### Description\\nParamiko 3.5.1 has a known vulnerability (CVE-2026-44405). No fix version is currently available.\\n\\n### Remediation Instructions\\nInvestigate whether paramiko can be upgraded to a newer version that addresses CVE-2026-44405. Check the paramiko changelog and security advisories. If no fix is available, document the risk and check if the vulnerable code path is exercised in Superset's usage of paramiko (used for SSH tunneling in database connections). If possible, pin to a safe version or add a code-level mitigation.\\n\\n### Acceptance Criteria\\n- [ ] Investigation documented in PR description\\n- [ ] If fix available: vulnerability no longer reported\\n- [ ] If no fix: risk assessment documented, mitigation applied if possible\\n- [ ] PR links back to this issue\\n\\n---\\n*Auto-generated by Security Remediation Pipeline*\"}" | python -c "import json,sys;d=json.load(sys.stdin);print(f'  Created issue #{d.get(\"number\",\"ERROR\")}: {d.get(\"html_url\",\"ERROR\")}')"

echo 4/4: eslint-plugin-i18n-strings malware GHSA-55h3-fm53-wq99
curl -s -X POST -H "%AUTH%" -H "%ACCEPT%" "%API%/repos/%SUPERSET_REPO%/issues" -d "{\"title\":\"[CRITICAL] GHSA-55h3-fm53-wq99: Remove malware package eslint-plugin-i18n-strings\",\"labels\":[\"devin-remediate\"],\"body\":\"## Security Vulnerability: GHSA-55h3-fm53-wq99\\n\\n**Package:** `eslint-plugin-i18n-strings` (npm)\\n**Severity:** CRITICAL\\n**Ecosystem:** npm\\n**Fix version:** No safe version exists - package contains malware\\n\\n### Description\\nThe npm package `eslint-plugin-i18n-strings` has been flagged as containing malware (GHSA-55h3-fm53-wq99). This package must be removed from the project entirely.\\n\\n### Remediation Instructions\\n1. Remove `eslint-plugin-i18n-strings` from `superset-frontend/package.json` (or wherever it is referenced)\\n2. Remove any ESLint configuration that references this plugin\\n3. If custom lint rules from this plugin are in use, migrate them to a safe alternative or implement them as local ESLint rules\\n4. Run `npm install` to update the lockfile\\n5. Run the linting and test suites to verify nothing is broken\\n\\n### Acceptance Criteria\\n- [ ] Package `eslint-plugin-i18n-strings` completely removed from dependencies and lockfile\\n- [ ] ESLint configuration updated to remove references to this plugin\\n- [ ] Linting still passes (with any rule migrations needed)\\n- [ ] All existing tests pass\\n- [ ] PR links back to this issue\\n\\n---\\n*Auto-generated by Security Remediation Pipeline*\"}" | python -c "import json,sys;d=json.load(sys.stdin);print(f'  Created issue #{d.get(\"number\",\"ERROR\")}: {d.get(\"html_url\",\"ERROR\")}')"

echo.
echo === All 4 issues created ===
echo Now trigger remediation: curl -X POST http://localhost:8000/api/trigger-all

endlocal
